# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GJazL8LdJNq32pn2uY3FZtOkrDbJ7V6W
"""

def add(a,b):
  sum=a+b
  print("Result is  = ",sum)