# -*- coding: utf-8 -*-
"""div.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iIyojqpYVcY_AwaYsCqsK9SoEuMZRhJ
"""

def divi(num1,num2):
  if num2 == 0:
    print("Invalid Input")
  else :
    print("Result is: ",num1/num2)