# -*- coding: utf-8 -*-
"""mul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvc_bX8oobfbr_O2r1pCpgOd2CTckXe9
"""

def mul(num1, num2):
    print('Result is: ', num1 * num2)