# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5R8RRBa9DKUkj1o04ChF52qp7tKkz7v
"""

def sub(a,b):
  print('The result is: ',a-b)